# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.yesButton = QtWidgets.QPushButton(self.centralwidget)
        self.yesButton.setGeometry(QtCore.QRect(580, 510, 93, 28))
        self.yesButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.yesButton.setCheckable(False)
        self.yesButton.setObjectName("yesButton")
        self.logTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.logTextEdit.setGeometry(QtCore.QRect(10, 30, 771, 171))
        self.logTextEdit.setObjectName("logTextEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 220, 131, 16))
        self.label_2.setObjectName("label_2")
        self.refButton = QtWidgets.QPushButton(self.centralwidget)
        self.refButton.setGeometry(QtCore.QRect(690, 510, 93, 28))
        self.refButton.setObjectName("refButton")
        self.revButton = QtWidgets.QPushButton(self.centralwidget)
        self.revButton.setGeometry(QtCore.QRect(10, 510, 93, 28))
        self.revButton.setObjectName("revButton")
        self.modifyList = QtWidgets.QListView(self.centralwidget)
        self.modifyList.setGeometry(QtCore.QRect(10, 250, 231, 221))
        self.modifyList.setObjectName("modifyList")
        self.domainList = QtWidgets.QListView(self.centralwidget)
        self.domainList.setGeometry(QtCore.QRect(250, 250, 281, 221))
        self.domainList.setObjectName("domainList")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 220, 131, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(540, 220, 131, 16))
        self.label_4.setObjectName("label_4")
        self.dnsList = QtWidgets.QListView(self.centralwidget)
        self.dnsList.setGeometry(QtCore.QRect(540, 250, 251, 221))
        self.dnsList.setObjectName("dnsList")
        self.addDomain = QtWidgets.QPushButton(self.centralwidget)
        self.addDomain.setGeometry(QtCore.QRect(440, 220, 93, 28))
        self.addDomain.setObjectName("addDomain")
        self.addDns = QtWidgets.QPushButton(self.centralwidget)
        self.addDns.setGeometry(QtCore.QRect(690, 220, 93, 28))
        self.addDns.setObjectName("addDns")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dns-Nice"))
        self.yesButton.setText(_translate("MainWindow", "开始"))
        self.label.setText(_translate("MainWindow", "日志"))
        self.label_2.setText(_translate("MainWindow", "已修改的Host"))
        self.refButton.setText(_translate("MainWindow", "刷新"))
        self.revButton.setText(_translate("MainWindow", "还原"))
        self.label_3.setText(_translate("MainWindow", "域名列表"))
        self.label_4.setText(_translate("MainWindow", "DNS列表"))
        self.addDomain.setText(_translate("MainWindow", "添加域名"))
        self.addDns.setText(_translate("MainWindow", "添加DNS"))
